### ISSUE TITLE
Cannot find module 'Vitrea-Client' or its corresponding type declarations.

### ISSUE THREAD

**Issue by smartnakh** [bdsoha/vitrea-client#33]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.

### Example Code

```node
import {
    ProtocolVersion,
    Requests,
    VitreaClient
} from 'Vitrea-Client'


const client = VitreaClient.create({
    host:     '192.168.1.111',
    port:     1234,
    username: 'admin',
    password: 'secret',
    version:  ProtocolVersion.V1
})

await client.connect()

await client.send(new Requests.RoomCount())
```

### Description

Hi,

I tried to compile the script and i am getting this error 

```
s@mbox:~/volumes/v2 $ sudo tsc index.ts
index.ts:5:8 - error TS2307: Cannot find module 'Vitrea-Client' or its corresponding type declarations.

5 } from 'Vitrea-Client'
         ~~~~~~~~~~~~~~~

index.ts:16:1 - error TS1378: Top-level 'await' expressions are only allowed when the 'module' option is set to 'es2022', 'esnext', 'system', 'node16', 'nodenext', or 'preserve', and the 'target' option is set to 'es2017' or higher.

16 await client.connect()
   ~~~~~

index.ts:18:1 - error TS1378: Top-level 'await' expressions are only allowed when the 'module' option is set to 'es2022', 'esnext', 'system', 'node16', 'nodenext', or 'preserve', and the 'target' option is set to 'es2017' or higher.

18 await client.send(new Requests.RoomCount())
   ~~~~~

Found 3 errors in the same file, starting at: index.ts:5

```
i  am using the include in the  tsconfig.json 
`   "include": ["src/**/*"]`

Please, help me to find what i am missing

### Package Version

1.0.0

### Protocol Version

V2 (Default)

### NodeJS Version

20.16.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by bdsoha** [comment]
Try `'vitrea-client'` with lowercase letters.

**Comment by smartnakh** [comment]
Thanks for your reply

i have still the same issue

```
error TS2307: Cannot find module 'vitrea-client' or its corresponding type declarations.

5 } from 'vitrea-client'
```

**Comment by bdsoha** [comment]
How did you install the package?

**Comment by smartnakh** [comment]
Thanks for your answer
```

smh@mbox:~/volumes/v2 $ npm list
gn@1.0.0 /home/smh/volumes/v2
└── vitrea-client@0.0.1-alpha.0 (git+ssh://git@github.com/bdsoha/vitrea-client.git#63ec5195c40fe15e363a3daa6de4b21468a18c45)

smh@mbox:~/volumes/v2 $ sudo npm install bdsoha/vitrea-client

up to date, audited 4 packages in 14s

found 0 vulnerabilities
smh@mbox:~/volumes/v2 $ 
```

**Comment by bdsoha** [comment]
Are you using TS?
Any compilers in place?

**Comment by smartnakh** [comment]
I am using tsc

**Comment by bdsoha** [comment]
Sorry for the hassle.

I just published a release *(alpha)*  to `npmjs.org`, which should resolve the proper creation of the `dist` folder in `node_modules`.
Try completely remove the existing dependency and reinstall it using `npm install vitrea-client` *(instead of via `git+ssh://...`.

**Comment by smartnakh** [comment]
Thanks for your help

i am getting this error
```
smh@mbox:/ $ sudo npm install vitrea-client
npm error Tracker "idealTree" already exists
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-08-26T07_54_19_971Z-debug-0.log
```

**Comment by bdsoha** [comment]
You are trying to install a package in the root directory `/`, that can't be done.
Move to a new folder and rerun the install:

```sh
mkdir /app
cd /app
npm init -y
npm install vitrea-client
```

**Comment by smartnakh** [comment]
thank you for you guidance

i got to this point 

```
smh@mbox:~/volumes/vitrea/app $ sudo nano app.ts
smh@mbox:~/volumes/vitrea/app $ sudo npx ts-node app.ts
/home/smh/volumes/node_modules/typescript/lib/typescript.js:2470
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at attemptRequireWithV8CompileCache (/usr/local/lib/node_modules/ts-node/dist/util.js:104:16)
    at loadCompiler (/usr/local/lib/node_modules/ts-node/dist/configuration.js:237:56)
    at resolveAndLoadCompiler (/usr/local/lib/node_modules/ts-node/dist/configuration.js:226:16)
npm ERR! code 1
npm ERR! path /home/smh/volumes/vitrea/app
npm ERR! command failed
npm ERR! command sh -c ts-node "app.ts"

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-08-27T07_31_05_593Z-debug.log
```
